Exception_of_num : forall ('e : Int), (0 <= 'e & 'e <= 18). int('e) -> Exception